### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by renepardon** [phphe/vue-draggable-nested-tree#106]
As soon as I import the tree component into my project's component (nothing more is required) it complains with the error described in the title.

I use following versions:
vue-draggable-nested-tree: "^2.2.18",
tree-helper: "^1.4.14",
draggable-helper: "^3.0.4",
node: v12.14.0
yarn: 1.10.1

```vue
<script>
    import Layout from '../../../components/Layout.vue'
    import {DraggableTree} from 'vue-draggable-nested-tree'
    // import {forIn} from 'tree-helper'
    // import _ from 'underscore'

    export default {
        name: 'MenuItemsEditPage',
        components: {
            Layout,
            Tree: DraggableTree
        },

...
```

**Comment by phphe** [comment]
Thank you for your use. I published he-tree-vue. vue-draggable-nested-tree will no longer be updated.
try this https://he-tree-vue.phphe.com/

**Comment by timrspratt** [comment]
Is there any chance you could fix this before stopping work on this package? It looks like it's just the `vue-draggable-nested-tree.min.js.map` that is out of date.

**Comment by phphe** [comment]
this should be caused by build. I added branch build-with-rogo, and published 3.0.0-beta. install by
```sh
npm install vue-draggable-nested-tree@3.0.0-beta --save
```
it should work well.

**Comment by judimator** [comment]
> this should be caused by build. I added branch build-with-rogo, and published 3.0.0-beta. install by
> 
> ```shell
> npm install vue-draggable-nested-tree@3.0.0-beta --save
> ```
> 
> it should work well.

dont work ^(
`vue-functions.esm.js?0eca:49 Uncaught ReferenceError: regeneratorRuntime is not defined
    at eval (vue-functions.esm.js?0eca:49)
    at Object../node_modules/vue-draggable-nested-tree/node_modules/vue-functions/dist/vue-functions.esm.js (app.js:932)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (vue-draggable-nested-tree.esm.js?e249:1)
    at Object../node_modules/vue-draggable-nested-tree/dist/vue-draggable-nested-tree.esm.js (app.js:908)`

**Comment by skiv1986** [comment]
> this should be caused by build. I added branch build-with-rogo, and published 3.0.0-beta. install by
> 
> ```shell
> npm install vue-draggable-nested-tree@3.0.0-beta --save
> ```
> 
> it should work well.

dont work anyway :(
`vue-functions.esm.js?0eca:49 Uncaught ReferenceError: regeneratorRuntime is not defined
    at eval (vue-functions.esm.js?0eca:49)
    at Object../node_modules/vue-draggable-nested-tree/node_modules/vue-functions/dist/vue-functions.esm.js (app.js:932)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (vue-draggable-nested-tree.esm.js?e249:1)
    at Object../node_modules/vue-draggable-nested-tree/dist/vue-draggable-nested-tree.esm.js (app.js:908)`

**Comment by phphe** [comment]
try vue-draggable-nested-tree@3.0.0-beta2
and remove node_modules, reinstall

**Comment by skiv1986** [comment]
> try vue-draggable-nested-tree@3.0.0-beta2
> and remove node_modules, reinstall

yes i uninstall vue-draggable-nested-tree
and install vue-draggable-nested-tree@3.0.0-beta 
but it still dont work
i need to reinstall all npm?

**Comment by phphe** [comment]
```sh
npm i -S vue-draggable-nested-tree@3.0.0-beta2
```
If still not work, remove node_modules, reinstall all
```sh
npm install
```

**Comment by phphe** [comment]
it is 3.0.0-beta2 not 3.0.0-beta. I just published it.

**Comment by renepardon** [comment]
Works perfectly, thx @phphe
