### ISSUE TITLE
Latest version appears to be broken on Windows Chrome and Firefox

### ISSUE THREAD

**Issue by shaydoc** [phphe/vue-draggable-nested-tree#13]
The latest version 2.0.2 seems to be broken on Windows with Chrome and Firefox when trying to drag, the drag event does not work. It works in Edge however

**Comment by phphe** [comment]
is there any error in console?

**Comment by frandisag** [comment]
i had this problem to.
if you using device with touch screen. please disable touch event on chrome.
it's work for me

**Comment by shaydoc** [comment]
@phphe this seems to be still broke on windows/chrome, any thoughts ?

**Comment by phphe** [comment]
@shaydoc I need error detail. tested in win7 chrome 61.0.3163.100 and Firefox Developer Edition, it works

**Comment by shaydoc** [comment]
@phphe, will get some info.
Its windows 10 and chrome laptop

**Comment by shaydoc** [comment]
The issue is dragging simply does not happen

**Comment by phphe** [comment]
@shaydoc what's the chrome version? and check is there any error output in Chrome console.

**Comment by shaydoc** [comment]
@phphe found the issue. the dell laptop i am testing on with chrome has touch events and mouse events, the touch screen is always on, therefore trackpad dragging does not work. drag-event-service.js therefore does not register the mouse start event.... need to register both touch and mouse events in this case
