### ISSUE TITLE
Alignment issue with adding a child node

### ISSUE THREAD

**Issue by taliesinmillhouse** [phphe/vue-draggable-nested-tree#15]
When adding a new child node to an existing node I'm getting an alignment issue. I am unable to drag the child node anywhere either. Once the parent node has been clicked, dragged and dropped the child node moves into the correct alignment and acts normally.

The code adding a new child.
`node.children.push({id: data.id, title: data.title, description: '', is_published: data.is_published});`

As you can see the 'Contact' node has a child but it's alignment is out.
![first](https://user-images.githubusercontent.com/30204322/43440223-dffa3ee8-94d9-11e8-9d41-ae8125f6bf66.PNG)

After the 'Contact' node has been dragged and dropped the child node moves into it's correct alignment.
![second](https://user-images.githubusercontent.com/30204322/43440267-0400140c-94da-11e8-8e50-333b50676ec9.PNG)

Let me know if you need any more information, thanks in advance!

**Comment by phphe** [comment]
i tried, it works in the latest vesion. check the second tree: the https://codepen.io/phphe/pen/KRapQm

**Comment by taliesinmillhouse** [comment]
Updating to the latest version fixed it. Thanks again.
