### ISSUE TITLE
i can not use even drop.help 

### ISSUE THREAD

**Issue by phamtuananh1996** [phphe/vue-draggable-nested-tree#16]
<Tree :data="data" cross-tree="cross-tree" draggable @drop="drop">
        <div slot-scope="{data, level, store}">
          <template v-if="!data.isDragPlaceHolder">
            <div class="node" @click="select(data)" v-bind:class="{ select: data.id==selectOrganization.id }">
              <b v-if="data.children &amp;&amp; data.children.length" @click="store.toggleOpen(data)">
                {{data.open ? '-' : '+'}}&nbsp;</b>
              <span>{{data.name}}</span>
              <span class="pull-right">
                  <status 
                  :status.sync= "data.status"
                  :options.sync = "options"
                  @approval = "approval(data)"
                  @rejection = "rejection(data)"
                />
                <button class="btn btn-primary btn-sm" @click="showAddModal(data)"><i class="fa fa-plus"></i></button>
                <button class="btn btn-warning btn-sm" @click="showEditModal(data)"><i class="fa fa-pencil"></i></button>
                <button class="btn btn-danger btn-sm" @click="destroy(data)"><i class="fa fa-remove"></i></button>
              </span>
            </div>
          </template>
        </div>
      </Tree>

**Comment by phphe** [comment]
I do not understand this issue. Please make it clear
