### ISSUE TITLE
Can only drag node once.  

### ISSUE THREAD

**Issue by mrkirchner** [phphe/vue-draggable-nested-tree#19]
Attached is sample template, JS. 

I am using vuex to fetch my data from server.  After moving an item once usually i am unable to drop that particular item again.  This usually happens if i move a child node out from parent.  If i dont do the treeChanged method everything seem fine.  Its only when i set tree data in change method or in vuex that the issue or bug occurs.

Template: 
`<DraggableTree :data="tree" :draggable="true" @change="treeChanged">`
 `<div slot-scope="{data, store}">`
   ` <template>`
       `<span>{{data.name}}</span>`
    ` </template>`
   `</div>`
`</DraggableTree>`

 
Data: 
`data() {`
    `      return { tree: JSON.parse(JSON.stringify(this.vuexData)) };`
 ` },`
  `methods: {`
    `    treeChanged(node, targetTree) {`
      `    this.tree = targetTree.getPureData();`
  `  },`
`  },`
Sorry for poor formating, Any help would be greatly appreciated.

**Comment by phphe** [comment]
i created a project for the issue on codepen: https://codepen.io/phphe/pen/bjOQxa
it works.
can you create a project on codepen?

**Comment by mrkirchner** [comment]
@phphe Thanks for looking into this i ended up creating the code pen but couldn't reproduce it either.  So i spent time looking at my code to figure out what caused it. It was just some weirdness i had between Vuex and Component.  Thanks Again
