### ISSUE TITLE
Set a max level child

### ISSUE THREAD

**Issue by kevindesousa** [phphe/vue-draggable-nested-tree#2]
Hello,

It's possible to set a max level child like this : 
![image](https://user-images.githubusercontent.com/4758092/40004438-ff9d195e-5795-11e8-8fb7-24d98f658633.png)

**Comment by phphe** [comment]
I published 2.0.0. I added 2 hooks isNodeDraggable, isNodeDroppable. You can use isNodeDroppable do that. Please check the demo: https://codepen.io/phphe/pen/KRapQm. The fourth tree meets your requirements.

**Comment by sdebacker** [comment]
@phphe I'm afraid there is some more work to do, it's possible to exceed the limit by dragging an item with children into another item.

**Comment by phphe** [comment]
@sdebacker You are right. I havn't any solution now.

**Comment by Heziode** [comment]
[Codepen](https://codepen.io/Heziode/pen/wxxPGR) of [MaxLevel.vue](https://github.com/phphe/vue-draggable-nested-tree/blob/master/src/examples/MaxLevel.vue) for quick test

**Comment by phphe** [comment]
> Hi @phphe
> 
> I have two Trees with cross-tree enabled, and I would like one flat, not the other.
> 
> I tried to limit depth to 1 on one of the tree with your code but it doesn't work in this context :
> from the behavior it seems the depth limit property is applied to each node instead of being applied to each tree.
> 
> I think a real and easy to use tree prop would be more than welcome !

I will think about it
