### ISSUE TITLE
Get the new node place info in Drop hook

### ISSUE THREAD

**Issue by MWStudio4** [phphe/vue-draggable-nested-tree#21]
Can i get the new parent info in dragend hook to reject dropping in some cases?

**Comment by phphe** [comment]
check hook ondragend: https://github.com/phphe/vue-draggable-nested-tree/blob/3ca6ce57cf6c4cfb0142c2d2ca5ebc8fc4812c70/src/components/DraggableTreeNode.vue
the argument 1 is the dragging node,
draggingNode.store: tree
draggingNode.store.dplh: plcaeholder
draggingNode.store.dplh.parent: new parent

**Comment by MWStudio4** [comment]
drop: (e, opt, store) => {
            const draggableHelperInfo = {event: e, options: opt, store}
            if (this.store.ondragend && this.store.ondragend(this.data, draggableHelperInfo) === false) { ...

These rows?

I have checked. There is no store in node (undefined)

**Comment by phphe** [comment]
sorry
draggingNode._vm.store: tree
draggingNode._vm.store.dplh: plcaeholder
draggingNode._vm.store.dplh.parent: new parent
