### ISSUE TITLE
After click on draggable item, certain elements on page become unresponsive.

### ISSUE THREAD

**Issue by filipbaranski** [phphe/vue-draggable-nested-tree#23]
As in title, I've found that whenever I click on an item in my tree, various elements (like paragraphs) become unresponsive. For instance: if I select part of paragraph (so it's highlited with blue background) and then click on item in the tree, this selection of paragraph cannot be removed. The only way to restore the proper behaviour is refreshing the page.
My guess is some kind of event fires but doesn't end since item wasn't moved (if item is moved this behaviour doesn't occur, however if item is clicked and then moved, it doesn't fix anything).

This bug is visible in examples provided on the main page (https://github.com/phphe/vue-draggable-nested-tree) - Base and MaxLevel. I tested it on newest Chrome, Firefox and Edge - all the same.

Is there some way to bypass that behaviour? My project requires usage of html editor, which becomes unresponsive when user accidentally clicks on an item in the tree.

**Comment by phphe** [comment]
do you mean this: https://drive.google.com/open?id=1JKPNYkG8O91Vw4fs-rq7IAootGzY0vXN

**Comment by filipbaranski** [comment]
No. In the example you've provided selection happens on items themselves. I meant other elements on page besides tree. Like paragraphs or headers.
The easiest way to replicate it would be:
1. Go to demo in codepen
2. Add "h1 test' above Tree component
3. Click on any item in the tree (but don't drag it)
4. See that you can't select 'test' in h1 you've added (that's what I meant by becoming unresponsive)

**Comment by phphe** [comment]
fixed in latest 2.1.5

**Comment by filipbaranski** [comment]
Works great. Thank you.
