### ISSUE TITLE
Bug in method pure()

### ISSUE THREAD

**Issue by anton-zaharov** [phphe/vue-draggable-nested-tree#3]
Hello,

I found an error in method pure()

pure(node, withChildren) {
      const t = Object.assign({}, node)
      delete t._id
      delete t.parent
      //delete t.children // do not remove childrens before recursion
      delete t.open
      delete t.level
      delete t.active
      delete t.style
      delete t.class
      delete t.innerStyle
      delete t.innerClass
      delete t.innerBackStyle
      delete t.innerBackClass
      for (const key of Object.keys(t)) {
        if (key.startsWith('_')) {   // it was key.startsWidth (!) 
          delete t[key]
        }
      }

**Comment by phphe** [comment]
can you show me error detail?
