### ISSUE TITLE
Node Position Within Level

### ISSUE THREAD

**Issue by fulopattila122** [phphe/vue-draggable-nested-tree#30]
First of all: cool component! :+1: 

How can I obtain the position of a node within a level?

**Example:**
I have 3 nodes: "Orange", "Banana" and "Kiwi" - all on the root level.
I drag the Banana node to the first position; just before Orange.
So the new order of the nodes will be "Banana", "Orange, "Kiwi".
Using the `@change` handler, how can I obtain if Banana became the first node?

Thank you!

**Comment by phphe** [comment]
do you mean node index? node.parent.children.indexOf(node)

**Comment by fulopattila122** [comment]
Yes, thanks!
