### ISSUE TITLE
Unable to get raw jason data after changing the nodes

### ISSUE THREAD

**Issue by sooraj007** [phphe/vue-draggable-nested-tree#34]
hi, my requirement is I want to save the node JSON data .. so whenever I change the node tree and console out the node array it outputs all dom kind of runtime properties. but I want to get newly modified JSON data in plain JSON format just data only . how can I achieve that.

Please Help me, please provide an example that would be very helpful.

**Comment by phphe** [comment]
check this: https://github.com/phphe/vue-draggable-nested-tree/issues/9
