### ISSUE TITLE
Support for multiple draggable items?

### ISSUE THREAD

**Issue by CesarBMartinez** [phphe/vue-draggable-nested-tree#35]
Is there support for multiple draggable, like "Windows Explorer?

![screenshot_6](https://user-images.githubusercontent.com/13169567/46834035-a3a7ef00-cd80-11e8-92cf-d997239556c4.png)

Thanks!

**Comment by phphe** [comment]
no. this is too difficult

**Comment by CesarBMartinez** [comment]
Ok, thanks.
