### ISSUE TITLE
TextEditor not clickable when within node when dragging=true, Enable Dragging only by selected child element

### ISSUE THREAD

**Issue by NeoMarine** [phphe/vue-draggable-nested-tree#36]
I am attempting to display a draggable (re-organizable) list of text editors, each editable by clicking on them (editable on click). The problem is, when :draggable="true", it will prevent all clicks passed to the text editor from triggering anything/working.

Additionally, I have successfully managed to enable dragging only when a child element (with ref="dragThis") to drag the element, but it only works if :draggable="true".

So, I am in a bit of a pickle it seems.

The text editor I am using is [Vue Medium Editor](https://github.com/FranzSkuffka/vue-medium-editor)

**Comment by phphe** [comment]
what's your version? or any demo?

**Comment by phphe** [comment]
i tried it on codepen: https://codepen.io/phphe/pen/ePqBwL it can't run. it is helpful if there is a demo on codepen

**Comment by NeoMarine** [comment]
Never used a codepen before - let me try and fix it for you!

**Comment by NeoMarine** [comment]
Here, I've got a demo working (finally) which demonstrates the issue.

Is it possible for you to:
a) Make it so that it ONLY drags when holding down on the "Hold to Drag" button.
b) Make it so that the editor is selectable within the tree.
c) (Additional feature request) Prevent moving the tree to any level other than level 1 (make it a non-nestable tree by simply setting a variable, e.g. "isNestable = false").

**Comment by phphe** [comment]
https://codepen.io/phphe/pen/gBVxbz
use getTriggerEl to set draggable element

**Comment by NeoMarine** [comment]
Thank you! I couldn't understand the documentation on getTriggerEl (I actually tried that also). I would think it's a good thing to include in your documentation (as an example) on how to set a child selector as draggable :)
