### ISSUE TITLE
demo那里的如果拖拽实例里面不存在数据，从别的实例拖拽到空的，会报错

### ISSUE THREAD

**Issue by zjhr** [phphe/vue-draggable-nested-tree#43]
目前还没使用该框架，但是从dome里面尝试了一下，当拖拽实例里面不存在数据，从别的实例拖拽到没数据那个空的实例，会报错，而且放不进去
[dome](https://codepen.io/phphe/pen/KRapQm)

**Comment by phphe** [comment]
fixed. 已修复
