### ISSUE TITLE
How to delete a node?

### ISSUE THREAD

**Issue by caiokawasaki** [phphe/vue-draggable-nested-tree#48]
How to use the method `deleteNode`?

**Comment by alucidwolf** [comment]
@caiokawasaki did you figure this out?

**Comment by caiokawasaki** [comment]
@alucidwolf yes! Simple:

```
<draggable-tree :data="steps" draggable="draggable">
    <div class="step" slot-scope="{data, store}">
        <template>
            <a class="delete-trigger" href="#" @click.prevent="deleteStep(data)">Deletar</a>
        </template>
    </div>
</draggable-tree>
```

Inside methods:

```
deleteStep(step) {
    this.deleteStepConfirmation._vm.store.deleteNode(step)
}
```

**Comment by alucidwolf** [comment]
@caiokawasaki Sweet! Thank you. I am using a Vuex store to render the data in a computed property, so once I remove the node, I call getPureData() and pass the new tree to a mutation to update the store.

```
<Tree :data="treeData" draggable="draggable">
  <div slot-scope="{data, store}">
    <div :class="data.children.length > 0 ? 'show-handle' : ''" v-if="!data.isDragPlaceHolder">
      <span @click="test(data, store)" class="icon-trash-alt"></span>
    </div>
  </div>
</Tree>
```

Method:
```
test(data, store) {
  store.deleteNode(data);

  let newData = store.getPureData();

  this.$store.commit("nestedDataTest/updateTree", [data]);
}
```

I am wondering if maybe I do not need to pass `store` down to the method just to access the getPureData() function on it. Will most likely move these into an action the delete and getPureData() then pass along the final object to a mutation.

Are you familiar with Vuex and have input on that? If not it's OK, you have helped me move forward already. Thanks again!

**Comment by caiokawasaki** [comment]
@alucidwolf I did not store the tree in the Vuex of my application... Sorry, I do not know how to help you = /
