### ISSUE TITLE
Is it support hierarchical table?

### ISSUE THREAD

**Issue by huiyang** [phphe/vue-draggable-nested-tree#54]
Seem like it do not support the hierarchical table as it use nested <TreeNode>?

I will need to display my records in table as it have many columns of data, is there any solution for this?

Thanks.

**Comment by phphe** [comment]
I don't know your needs. Could you give more information? pic, code or demo

**Comment by huiyang** [comment]
I need to do something like this:
It is multiple level, and draggable,
also, it is in a table, so that i can put button, or other information in each line
<table><tr><td></td></tr></table>

![image](https://user-images.githubusercontent.com/517651/51981584-7bc6cd80-24ce-11e9-8303-14c3334492b6.png)

Thanks.

**Comment by phphe** [comment]
that is easy.
there is a button for every node in below example:
```pug
Tree(:data="data" draggable crossTree)
  div(slot-scope="{data, store, vm}")
    //- data is node
    //- store is the tree
    //- vm is node Vue instance, you can get node level by vm.level
    template(v-if="!data.isDragPlaceHolder")
      b(v-if="data.children && data.children.length" @click="store.toggleOpen(data)") {{data.open ? '-' : '+'}}&nbsp;
      span {{data.text}}
      button your button
```

**Comment by huiyang** [comment]
but this is not in a table, the button is not aligned

**Comment by phphe** [comment]
it don't support hierarchical table. you can use css to align it.

**Comment by huiyang** [comment]
Oh, alright, thanks.
