### ISSUE TITLE
Dragging Items Below Viewport

### ISSUE THREAD

**Issue by nzshumate** [phphe/vue-draggable-nested-tree#62]
The class `dragging` is added to a node when it is being dragged. It is also adding inline styles with `position: absolute; top: ${someValue}`. I am noticing, in my case, that if an item is below the initial viewport its position is off by the height of the viewport that was hidden on the initial page render.

I am using v2.2.8 on Chrome.

**Comment by phphe** [comment]
can you make a demo on codepen or jsfiddle or other?

**Comment by nzshumate** [comment]
Thanks, I was actually able to hunt down the issue.. It was something on my end that was breaking it.
