### ISSUE TITLE
How to specify a drag handler ?

### ISSUE THREAD

**Issue by mazentouati** [phphe/vue-draggable-nested-tree#63]
Hey there,
I'm wondering how to specify a element to be used as the drag handler ?

In case you don't understand what I meant, it basically would be something like this

![Capture](https://user-images.githubusercontent.com/14861869/54154812-0c37ec80-4443-11e9-92e2-8b8225406a7d.PNG)

**Comment by phphe** [comment]
https://github.com/phphe/vue-draggable-nested-tree#tree-props
example: getTriggerEl(nodeVm){ return nodeVm.$el.querySelector('.drag-handler') }

**Comment by mazentouati** [comment]
Thanks for providing the example 👍 , I stumbled upon that method and it confused me as it's unconventional, it would be more helpful if the name was `setTriggerEl()`.
