### ISSUE TITLE
rtl languages

### ISSUE THREAD

**Issue by suliemansh** [phphe/vue-draggable-nested-tree#7]
can you add an option for rtl languages ?
making the drag from right

**Comment by phphe** [comment]
@suliemansh Sorry, I may not be able to complete this feature in a short time

**Comment by nekooee** [comment]
pleaseeeee add this option

**Comment by phphe** [comment]
Thank you for your use. I published he-tree-vue. vue-draggable-nested-tree will no longer be updated.
try this https://he-tree-vue.phphe.com/
