### ISSUE TITLE
Cannot find module 'core-js/library/fn/object/keys'

### ISSUE THREAD

**Issue by ben-roth** [phphe/vue-draggable-nested-tree#79]
After I run `npm install vue-draggable-nested-tree` I receive this error "Cannot find module 'core-js/library/fn/object/keys'", 

It seems like core-js has changed a lot and now there are a bunch of broken dependencies.

**Comment by phphe** [comment]
I created a test at https://codesandbox.io/s/vue-template-ejc2h
I can not get the error

**Comment by vjee** [comment]
@ben-roth Are you using `core-js@3` in your project?
The import path does not exists in core-js 3 but it does under version 2.
I'm running into the same issues.

**Comment by vjee** [comment]
Try `import ... from "vue-draggable-nested-tree/dist/vue-draggable-nested-tree.js"` instead of `import ... from "vue-draggable-nested-tree"`.

This file will have all the `core-js` requirements included so if you get these errors because of a version mismatch, it should work.

**Comment by ben-roth** [comment]
@vjee yes, that's my issue. Odd though that we have to specify like that?
