### ISSUE TITLE
能不能和vue-draggable一样加一个拖入的目标树在钩子方法ondragend的参数中

### ISSUE THREAD

**Issue by lt125327422** [phphe/vue-draggable-nested-tree#80]
因为业务要根据拖动的目标树来判断是否允许拖拽，drop事件可以获取到targetTree，但是不能根据return的值来判断是否进行拖拽，而且这个方法还在ondragend之后执行也不能通过设置全局变量的方式来传递

**Comment by phphe** [comment]
target tree: node._vm.store.dplh._vm.store
就是占位符所属的树

**Comment by lt125327422** [comment]
真的非常感谢你！
