### ISSUE TITLE
How to set innerBackStyle?

### ISSUE THREAD

**Issue by merlinschumacher** [phphe/vue-draggable-nested-tree#85]
It's unclear to me how I can set innerBackStyle of the TreeNodes.

**Comment by phphe** [comment]
```pug
.tree-node-inner-back(:style="[innerBackStyle, data.innerBackStyle]" :class="[data.innerBackClass]")
```
just assign to data.innerBackStyle

**Comment by merlinschumacher** [comment]
What i wanted to achieve was actually to get rid of the inline CSS added to "tree-node-inner-back". The px-values seem to inflexible.

**Comment by phphe** [comment]
the px-values is used to calc when drag, so change is difficult
