### ISSUE TITLE
Pushing data to tree results in error

### ISSUE THREAD

**Issue by ben-roth** [phphe/vue-draggable-nested-tree#86]
A simple push of data to my tree results in the following error. Have no idea why, any thoughts  or ideas???

**My push code** 

`app.data.push({title:"New"})`

**the error i get:**

```
[Vue warn]: Error in render: "TypeError: Cannot read property '0' of undefined"

found in

---> <TreeNode> at DraggableTreeNode.vue... (1 recursive calls)
       <Tree> at DraggableTree.vue
         <Root>
```

**Comment by phphe** [comment]
what is the error line

**Comment by ben-roth** [comment]
1138

**return [t._t("default", null, {**

`scopedSlots: t._u([{
          key: "default",
          fn: function fn(e) {
            return [t._t("default", null, {
              data: e.data,
              store: t.store,
              vm: e.vm
            })];
          }
        }`

**Comment by phphe** [comment]
what's your template? I suspect that your template has a problem.

**Comment by ben-roth** [comment]
ahh, thank you so much, there was an issue with my template. Thank you!
