### ISSUE TITLE
manual update call to force the tree to refresh

### ISSUE THREAD

**Issue by ben-roth** [phphe/vue-draggable-nested-tree#88]
I have want to have a second method of selecting a nodes parent, however I want to trigger the tree to rebuild once I use this other method of changing a nodes parent. Is there any way to force the tree to rebuild based on information I am passing without using the traditional drag method?

Thanks!

**Comment by phphe** [comment]
I don't understand.

**Comment by ben-roth** [comment]
Basically I am changing the data the tree is using without using the drag method, is there a way to update the tree in the view manually via a change method or something like that?

**Comment by phphe** [comment]
```js
data = tree.getPureData()
```
to trigger watch changed

**Comment by ben-roth** [comment]
Thanks!

**Comment by scyuan** [comment]
@ben-roth How do you solve it?
