### ISSUE TITLE
Disable nesting for specific tree

### ISSUE THREAD

**Issue by ben-roth** [phphe/vue-draggable-nested-tree#92]
I have 2 trees, I want to disable nesting in one tree so that I can't nest any children but I want to be able to keep nesting working in the other tree. Is there a way I can do this by tree? Thank you!

**Comment by phphe** [comment]
make the data not nested, then the tree will not be nested. If you just want the tree with nesting data looks not nested, pass tree prop `indent` 0
```html
<Tree :indent="0">
```

**Comment by ben-roth** [comment]
> make the data not nested

I understand that, but when dragging nodes around, they can easily "nest" even if they look like they are not nested by using indent="0" that will still nest the data no? Or will indent="0" prevent drag nesting?

**Comment by phphe** [comment]
set all node 'droppable=false'

**Comment by ben-roth** [comment]
Thanks!
