### ISSUE TITLE
Helper.js triggering CSP for inline style

### ISSUE THREAD

**Issue by tbeenpwn** [phphe/vue-draggable-nested-tree#97]
Hey phphe,

firstly thank you for developing this component. I use this embedded in an iFrame and the restoreAttr function in your helper triggers the CSP. Do you have any tip for this?

**Comment by phphe** [comment]
Can you reproduce the issue? Actually, the Codepen demo is in  iFrame and it works well. https://codepen.io/phphe/pen/KRapQm

**Comment by tbeenpwn** [comment]
Yes, as CodePen allows inline styling. My error evolves around "style-src 'self'" being forbidden. I just figured setting the style via the .style will solve it. Time to fork this. Thank you!
